const foodItem = [
  {
    id: 1,
    name: "Ambur Biryani",
    category: "biryani",
    rating: 4.3,
    price: 13,
    img: "assets/Briyani/AmburChicken.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Chicken Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "assets/Briyani/ChickenBriyani.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Fish Biryani",
    category: "biryani",
    rating: 4.3,
    price: 18,
    img: "assets/Briyani/FishBriyani.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Kamprupi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "asstes/Briyani/KamprupiBriyani.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "kashmiri Biryani",
    category: "biryani",
    rating: 4.3,
    price: 10,
    img: "assets/Briyani/KashmiriBriyani.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 12,
    img: "assets/Briyani/MemoniBryani.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Mutton Biryani",
    category: "biryani",
    rating: 4.3,
    price: 13,
    img: "assets/Briyani/MuttonBiryani.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 20,
    img: "assets/Briyani/MemoniBryani.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Mughlai Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "assets/briyani/MughlaiBryani.jpg",
    quantity: 1,
  },
  {
    id: 10,
    name: "Chicken Roast",
    category: "chicken",
    rating: 4.3,
    price: 11,
    img: "assets/Chicken/Chicken_roast.jpg",
    quantity: 1,
  },
  {
    id: 11,
    name: "Chicken Curry",
    category: "chicken",
    rating: 4.3,
    price: 10,
    img: "assets/Chicken/Chicken-Curry.jpg",
    quantity: 1,
  },
  {
    id: 12,
    name: "Chicken Do Pyaza",
    category: "chicken",
    rating: 4.3,
    price: 14,
    img: "assets/Chicken/Chicken-do-pyaza.jpg",
    quantity: 1,
  },
  {
    id: 13,
    name: "Chicken Masala",
    category: "chicken",
    rating: 4.3,
    price: 12,
    img: "assets/Chicken/Chicken-Masala.jpg",
    quantity: 1,
  },
  {
    id: 14,
    name: "Handi Chicken",
    category: "chicken",
    rating: 4.3,
    price: 17,
    img: "assets/Chicken/Handi-chicken.jpg",
    quantity: 1,
  },
  {
    id: 15,
    name: "Murgh Musallam",
    category: "chicken",
    rating: 4.3,
    price: 20,
    img: "assets/Chicken/Murgh-Musallam.jpg",
    quantity: 1,
  },
  {
    id: 16,
    name: "Cabbage Momos",
    category: "ChinaFood",
    rating: 4.3,
    price: 15,
    img: "assets/ChinaFood/cabbage-momos.jpg",
    quantity: 1,
  },
  {
    id: 17,
    name: "Chicken Manchurian",
    category: "ChinaFood",
    rating: 4.3,
    price: 10,
    img: "assets/ChinaFood/ChickenManchurian.jpg",
    quantity: 1,
  },
  {
    id: 18,
    name: "ChinaFood Butter Masala",
    category: "ChinaFood",
    rating: 4.3,
    price: 15,
    img: "",
    quantity: 1,
  },
  {
    id: 19,
    name: "ChinaFood Do Pyaza",
    category: "ChinaFood",
    rating: 4.3,
    price: 12,
    img: "",
    quantity: 1,
  },
  {
    id: 20,
    name: "Hyderabadi ChinaFood",
    category: "ChinaFood",
    rating: 4.3,
    price: 8,
    img: "",
    quantity: 1,
  },
  {
    id: 21,
    name: "ChinaFood Lababdar",
    category: "ChinaFood",
    rating: 4.3,
    price: 7,
    img: "",
    quantity: 1,
  },
  {
    id: 22,
    name: "Shahi ChinaFood",
    age: "32",
    category: "ChinaFood",
    rating: 4.3,
    price: 5,
    img: "",
    quantity: 1,
  },
  {
    id: 23,
    name: "Navratan Korma",
    category: "vegetable",
    rating: 4.3,
    price: 8,
    img: "",
    quantity: 1,
  },
  {
    id: 24,
    name: "Veg Jalfrezi",
    category: "vegetable",
    rating: 4.3,
    price: 7,
    img: "",
    quantity: 1,
  },
  {
    id: 25,
    name: "Veg Biryani",
    category: "vegetable",
    rating: 4.3,
    price: 5,
    img: "",
    quantity: 1,
  },
  {
    id: 26,
    name: "Veg Curry",
    category: "vegetable",
    rating: 4.3,
    price: 7,
    img: "",
    quantity: 1,
  },
  {
    id: 27,
    name: "Veg Kolhapur",
    category: "vegetable",
    rating: 4.3,
    price: 10,
    img: "",
    quantity: 1,
  },
  {
    id: 28,
    name: "Veg Masala",
    category: "vegetable",
    rating: 4.3,
    price: 4,
    img: "",
    quantity: 1,
  },
  {
    id: 29,
    name: "Veg Pakora",
    category: "vegetable",
    rating: 4.3,
    price: 4,
    img: "",
    quantity: 1,
  },
  {
    id: 30,
    name: "Momos",
    category: "chinese",
    rating: 4.3,
    price: 8,
    img: "",
    quantity: 1,
  },
  {
    id: 31,
    name: "Chicken Manchurian",
    category: "chinese",
    rating: 4.3,
    price: 7,
    img: "",
    quantity: 1,
  },
  {
    id: 32,
    name: "Chili Chicken",
    category: "chinese",
    rating: 4.3,
    price: 5,
    img: "",
    quantity: 1,
  },
  {
    id: 33,
    name: "Chowmein",
    category: "chinese",
    rating: 4.3,
    price: 16,
    img: "",
    quantity: 1,
  },
  {
    id: 34,
    name: "Spring Roll",
    category: "chinese",
    rating: 4.3,
    price: 14,
    img: "",
    quantity: 1,
  },
  {
    id: 35,
    name: "Szechuan Chicken",
    category: "chinese",
    rating: 4.3,
    price: 10,
    img: "",
    quantity: 1,
  },
  {
    id: 36,
    name: "Fried Rice",
    category: "chinese",
    rating: 4.3,
    price: 8,
    img: "",
    quantity: 1,
  },
  {
    id: 37,
    name: "Butter Masala Dosa",
    category: "south indian",
    rating: 4.3,
    price: 18,
    img: "",
    quantity: 1,
  },
  {
    id: 38,
    name: "Idli",
    category: "south indian",
    rating: 4.3,
    price: 20,
    img: "",
    quantity: 1,
  },
  {
    id: 39,
    name: "Masala Dosa",
    category: "south indian",
    rating: 4.3,
    price: 12,
    img: "",
    quantity: 1,
  },
  {
    id: 40,
    name: "Mysore Bonda",
    category: "south indian",
    rating: 4.3,
    price: 10,
    img: "",
    quantity: 1,
  },
  {
    id: 41,
    name: "Onion Uttapam",
    category: "south indian",
    rating: 4.3,
    price: 15,
    img: "",
    quantity: 1,
  },
  {
    id: 42,
    name: "Plain Dosa",
    category: "south indian",
    rating: 4.3,
    price: 40,
    img: "",
    quantity: 1,
  },
  {
    id: 43,
    name: "Rava Uttapam",
    category: "south indian",
    rating: 4.3,
    price: 25,
    img: "",
    quantity: 1,
  },
  {
    id: 44,
    name: "Sambhar Vada",
    category: "south indian",
    rating: 4.3,
    price: 34,
    img: "",
    quantity: 1,
  },
];

export { foodItem };
