const foodItem = [
  {
    id: 1,
    name: "Ambur Biryani",
    category: "biryani",
    rating: 4.3,
    price: 13,
    img: "assets/Briyani/AmburChicken.jpg",
    quantity: 1,
  },
  {
    id: 2,
    name: "Chicken Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "assets/Briyani/ChickenBriyani.jpg",
    quantity: 1,
  },
  {
    id: 3,
    name: "Fish Biryani",
    category: "biryani",
    rating: 4.3,
    price: 18,
    img: "assets/Briyani/FishBriyani.jpg",
    quantity: 1,
  },
  {
    id: 4,
    name: "Kamprupi Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "asstes/Briyani/KamprupiBriyani.jpg",
    quantity: 1,
  },
  {
    id: 5,
    name: "kashmiri Biryani",
    category: "biryani",
    rating: 4.3,
    price: 10,
    img: "assets/Briyani/KashmiriBriyani.jpg",
    quantity: 1,
  },
  {
    id: 6,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 12,
    img: "assets/Briyani/MemoniBryani.jpg",
    quantity: 1,
  },
  {
    id: 7,
    name: "Mutton Biryani",
    category: "biryani",
    rating: 4.3,
    price: 13,
    img: "assets/Briyani/MuttonBiryani.jpg",
    quantity: 1,
  },
  {
    id: 8,
    name: "Memoni Biryani",
    category: "biryani",
    rating: 4.3,
    price: 20,
    img: "assets/Briyani/MemoniBryani.jpg",
    quantity: 1,
  },
  {
    id: 9,
    name: "Mughlai Biryani",
    category: "biryani",
    rating: 4.3,
    price: 15,
    img: "assets/briyani/MughlaiBryani.jpg",
    quantity: 1,
  },
  {
    id: 10,
    name: "Chicken Roast",
    category: "chicken",
    rating: 4.3,
    price: 11,
    img: "assets/Chicken/Chicken_roast.jpg",
    quantity: 1,
  },
  {
    id: 11,
    name: "Chicken Curry",
    category: "chicken",
    rating: 4.3,
    price: 10,
    img: "assets/Chicken/Chicken-Curry.jpg",
    quantity: 1,
  },
  {
    id: 12,
    name: "Chicken Do Pyaza",
    category: "chicken",
    rating: 4.3,
    price: 14,
    img: "assets/Chicken/Chicken-do-pyaza.jpg",
    quantity: 1,
  },
  {
    id: 13,
    name: "Chicken Masala",
    category: "chicken",
    rating: 4.3,
    price: 12,
    img: "assets/Chicken/Chicken-Masala.jpg",
    quantity: 1,
  },
  {
    id: 14,
    name: "Handi Chicken",
    category: "chicken",
    rating: 4.3,
    price: 17,
    img: "assets/Chicken/Handi-chicken.jpg",
    quantity: 1,
  },
  {
    id: 15,
    name: "Murgh Musallam",
    category: "chicken",
    rating: 4.3,
    price: 20,
    img: "assets/Chicken/Murgh-Musallam.jpg",
    quantity: 1,
  },
  {
    id: 16,
    name: "Cabbage Momos",
    category: "ChinaFood",
    rating: 4.3,
    price: 15,
    img: "assets/ChinaFood/cabbage-momos.jpg",
    quantity: 1,
  },
  {
    id: 17,
    name: "Chicken Manchurian",
    category: "ChinaFood",
    rating: 4.3,
    price: 10,
    img: "assets/ChinaFood/ChickenManchurian.jpg",
    quantity: 1,
  },
  {
    id: 18,
    name: "Chili Chicken",
    category: "ChinaFood",
    rating: 4.3,
    price: 15,
    img: "assets/ChinaFood/Chili-Chicken.jpg",
    quantity: 1,
  },
  {
    id: 19,
    name: "chowmin",
    category: "ChinaFood",
    rating: 4.3,
    price: 12,
    img: "assets/ChinaFood/chowmin.jpg",
    quantity: 1,
  },
  {
    id: 20,
    name: "mmos",
    category: "ChinaFood",
    rating: 4.3,
    price: 8,
    img: "asstes/ChinaFood/mmos.jpg",
    quantity: 1,
  },
  {
    id: 21,
    name: "spring rolls",
    category: "ChinaFood",
    rating: 4.3,
    price: 7,
    img: "assets/ChinaFood/spring-rolls.jpg",
    quantity: 1,
  },
  {
    id: 22,
    name: "Shahi ChinaFood",
    category: "ChinaFood",
    rating: 4.3,
    price: 5,
    img: "assets/ChinaFood/szechuan-chicken.jpg",
    quantity: 1,
  },
  {
    id: 23,
    name: "Beef Yakiniku",
    category: "JapanesseFood",
    rating: 4.3,
    price: 8,
    img: "assets/BeefYakiniku.jpg",
    quantity: 1,
  },
  {
    id: 24,
    name: "Mochi",
    category: "JapanesseFood",
    rating: 4.3,
    price: 7,
    img: "assets/JapanesseFood/mochi.jpg",
    quantity: 1,
  },
  {
    id: 25,
    name: "Okonomiyaki",
    category: "JapanesseFood",
    rating: 4.3,
    price: 5,
    img: "assets/JapanesseFood/okonomiyaki.jpg",
    quantity: 1,
  },
  {
    id: 26,
    name: "ramen",
    category: "JapanesseFood",
    rating: 4.3,
    price: 7,
    img: "aasets/JapanesseFood/ramen.jpg",
    quantity: 1,
  },
  {
    id: 27,
    name: "sashimi",
    category: "JapanesseFood",
    rating: 4.3,
    price: 10,
    img: "assets/JapanesseFood/sashimi.jpg",
    quantity: 1,
  },
  {
    id: 28,
    name: "Shusi",
    category: "JapanesseFood",
    rating: 4.3,
    price: 4,
    img: "assets/JapanesseFood/sushi.jpg",
    quantity: 1,
  },
  {
    id: 29,
    name: "takoyaki",
    category: "JapanesseFood",
    rating: 4.3,
    price: 4,
    img: "assets/JapanesseFood/takoyaki.jpg",
    quantity: 1,
  },
  {
    id: 30,
    name: "bibimbap",
    category: "KoreanFood",
    rating: 4.3,
    price: 8,
    img: "assets/KoreanFood/bibimbap.jpg",
    quantity: 1,
  },
  {
    id: 31,
    name: "bulgogi",
    category: "KoreanFood",
    rating: 4.3,
    price: 7,
    img: "assets/KoreanFood/bulgogi.jpg",
    quantity: 1,
  },
  {
    id: 32,
    name: "japchae",
    category: "KoreanFood",
    rating: 4.3,
    price: 5,
    img: "assets/KoreanFood/japchae.jpg",
    quantity: 1,
  },
  {
    id: 33,
    name: "Kimchi Jjigae",
    category: "KoreanFood",
    rating: 4.3,
    price: 16,
    img: "assets/KoreanFood/Kimchi-Jjigae.jpg",
    quantity: 1,
  },
  {
    id: 34,
    name: "Kimchi",
    category: "KoreanFood",
    rating: 4.3,
    price: 14,
    img: "assets/KoreanFood/kimchi",
    quantity: 1,
  },
  {
    id: 35,
    name: "Samgyeopsal",
    category: "KoreanFood",
    rating: 4.3,
    price: 10,
    img: "assets/KoreanFood/Samgyeopsal.jpg",
    quantity: 1,
  },
  {
    id: 36,
    name: "Ttekbokki",
    category: "KoreanFood",
    rating: 4.3,
    price: 8,
    img: "assets/KoreanFood/ttekbokki",
    quantity: 1,
  },
  {
    id: 37,
    name: "Navratan",
    category: "Vegetable",
    rating: 4.3,
    price: 18,
    img: "",
    quantity: 1,
  },
  {
    id: 38,
    name: "Idli",
    category: "Vegetable",
    rating: 4.3,
    price: 20,
    img: "",
    quantity: 1,
  },
  {
    id: 39,
    name: "Masala Dosa",
    category: "Vegetable",
    rating: 4.3,
    price: 12,
    img: "",
    quantity: 1,
  },
  {
    id: 40,
    name: "Mysore Bonda",
    category: "Vegetable",
    rating: 4.3,
    price: 10,
    img: "",
    quantity: 1,
  },
  {
    id: 41,
    name: "Onion Uttapam",
    category: "Vegetable",
    rating: 4.3,
    price: 15,
    img: "",
    quantity: 1,
  },
  {
    id: 42,
    name: "Plain Dosa",
    category: "Vegetable",
    rating: 4.3,
    price: 40,
    img: "",
    quantity: 1,
  },
  {
    id: 43,
    name: "Rava Uttapam",
    category: "Vegetable",
    rating: 4.3,
    price: 25,
    img: "",
    quantity: 1,
  },
  {
    id: 44,
    name: "Sambhar Vada",
    category: "Vegetable",
    rating: 4.3,
    price: 34,
    img: "",
    quantity: 1,
  },
];

export { foodItem };
